--liquibase formatted sql

--changeset filas:1
CREATE TABLE proposta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposta BIGINT,
    origem VARCHAR(100),
    fila_atual VARCHAR(100),
    perfil VARCHAR(100),
    cliente_cpf VARCHAR(20),
    grupo2 VARCHAR(100),
    agente_nome VARCHAR(150),
    agente_codigo VARCHAR(50),
    cidade VARCHAR(150),
    lojista_nome VARCHAR(150),
    tipo_cliente VARCHAR(100),
    tipo_lojista VARCHAR(100),
    data_criacao TIMESTAMP,
    data_ultimo_envio_fila TIMESTAMP,
    atualizado_em TIMESTAMP
);
--rollback DROP TABLE proposta;

--changeset filas:2
CREATE TABLE atributo_proposta (
    atributo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposta_id BIGINT,
    cliente_nome VARCHAR(150),
    cliente_perfil VARCHAR(100),
    cliente_classificacao INTEGER,
    operador_nome VARCHAR(150),
    operador_codigo VARCHAR(50),
    agente_classificacao VARCHAR(100),
    lojista_classificacao VARCHAR(100),
    valor_credito DECIMAL(19,2),
    entrada_percentual DECIMAL(19,2),
    "local" INTEGER,
    numero_devolucoes INTEGER,
    atualizado_em TIMESTAMP,
    CONSTRAINT fk_atributo_proposta_proposta FOREIGN KEY (proposta_id)
        REFERENCES proposta (id) ON DELETE CASCADE
);
--rollback DROP TABLE atributo_proposta;

--changeset filas:3
CREATE TABLE analise (
    id_analise BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposta_id BIGINT NOT NULL,
    tipo_fila VARCHAR(100),
    data_entrada TIMESTAMP,
    data_inicio TIMESTAMP,
    analista_atribuido_id VARCHAR(100),
    analista_atual_id VARCHAR(100),
    prioridade VARCHAR(50),
    CONSTRAINT fk_analise_proposta FOREIGN KEY (proposta_id)
        REFERENCES proposta (id) ON DELETE CASCADE
);
--rollback DROP TABLE analise;

--changeset filas:4
CREATE INDEX idx_analise_proposta ON analise (proposta_id);
--rollback DROP INDEX idx_analise_proposta;


INSERT INTO proposta (
    proposta,
    origem,
    fila_atual,
    perfil,
    cliente_cpf,
    grupo2,
    agente_nome,
    agente_codigo,
    cidade,
    lojista_nome,
    tipo_cliente,
    tipo_lojista,
    data_criacao,
    data_ultimo_envio_fila,
    atualizado_em
) VALUES
(
    1001,
    'omni+',
    'ANALISE',
    'PADRAO',
    '12345678900',
    'G1',
    'João Silva',
    '330',
    'São Paulo',
    'Loja Centro',
    'PF',
    'FISICO',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    1002,
    'omnifacil',
    'APROVACAO',
    'VIP',
    '98765432100',
    'G2',
    'Maria Souza',
    '330',
    'Campinas',
    'Loja Norte',
    'PF',
    'FISICO',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    1003,
    'outro',
    'REPROVADO',
    'PADRAO',
    '11122233344',
    'G1',
    'Carlos Lima',
    '999',
    'Rio de Janeiro',
    'Loja Sul',
    'PJ',
    'ONLINE',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
