--liquibase formatted sql

--changeset filas:1
CREATE TABLE proposta (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    proposta NUMBER,
    origem VARCHAR2(100),
    fila_atual VARCHAR2(100),
    perfil VARCHAR2(100),
    cliente_cpf VARCHAR2(20),
    grupo2 VARCHAR2(100),
    agente_nome VARCHAR2(150),
    agente_codigo VARCHAR2(50),
    cidade VARCHAR2(150),
    lojista_nome VARCHAR2(150),
    tipo_cliente VARCHAR2(100),
    tipo_lojista VARCHAR2(100),
    data_criacao TIMESTAMP,
    data_ultimo_envio_fila TIMESTAMP,
    atualizado_em TIMESTAMP
);
--rollback DROP TABLE proposta;

--changeset filas:2
CREATE TABLE atributo_proposta (
    atributo_id number PRIMARY KEY,
    proposta_id NUMBER ,
    cliente_nome VARCHAR2(150),
    cliente_perfil VARCHAR2(100),
    cliente_classificacao NUMBER,
    operador_nome VARCHAR2(150),
    operador_codigo VARCHAR2(50),
    agente_classificacao VARCHAR2(100),
    lojista_classificacao VARCHAR2(100),
    valor_credito NUMBER(19,2),
    entrada_percentual NUMBER(19,2),
    local NUMBER,
    numero_devolucoes NUMBER,
    atualizado_em TIMESTAMP,
    CONSTRAINT fk_atributo_proposta_proposta FOREIGN KEY (proposta_id) REFERENCES proposta (id) ON DELETE CASCADE
);
--rollback DROP TABLE atributo_proposta;

--changeset filas:3
CREATE TABLE analise (
    id_analise NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    proposta_id NUMBER NOT NULL,
    tipo_fila VARCHAR2(100),
    data_entrada TIMESTAMP,
    data_inicio TIMESTAMP,
    analista_atribuido_id VARCHAR2(100),
    analista_atual_id VARCHAR2(100),
    prioridade VARCHAR2(50),
    CONSTRAINT fk_analise_proposta FOREIGN KEY (proposta_id) REFERENCES proposta (id) ON DELETE CASCADE
);
--rollback DROP TABLE analise;

--changeset filas:4
CREATE INDEX idx_analise_proposta ON analise (proposta_id);
--rollback DROP INDEX idx_analise_proposta;
